import { create } from "zustand";
import { persist } from "zustand/middleware";

// ── Types ──────────────────────────────────────────────────────────────────

export type ClimateZone =
  | "composite"
  | "hot_dry"
  | "warm_humid"
  | "temperate"
  | "cold"
  | null;

export type BuildingType = "low_rise" | "affordable" | "high_rise" | null;

export type ArchStyle =
  | "modern"
  | "traditional"
  | "vernacular"
  | "minimalist"
  | null;

export type BudgetRange =
  | "under_30L"
  | "30L_60L"
  | "60L_1Cr"
  | "above_1Cr"
  | null;

export interface PlotLocation {
  lat: number;
  lng: number;
  address: string;
  city: string;
  state: string;
}

export interface Requirements {
  bedrooms: number;
  bathrooms: number;
  livingRooms: number;
  kitchen: number;
  parkingBays: number;
  openSpacePercent: number; // % of plot for open space
  floors: number;
  buildingType: BuildingType;
  plotAreaSqm: number;
  plotFacing: "north" | "south" | "east" | "west" | null;
  hasElderly: boolean;
  hasHomeOffice: boolean;
  vastuPreference: boolean;
}

export interface ClimateData {
  zone: ClimateZone;
  avgTempSummer: number;
  avgTempWinter: number;
  humidity: string;
  prevailingWind: string;
  peakSunHours: number;
  bestOrientation: string;
}

export interface ProjectStore {
  // Step 1
  location: PlotLocation | null;
  climateData: ClimateData | null;

  // Step 2
  requirements: Requirements;

  // Step 3 — generated by engine
  ensScore: number | null;
  layoutSuggestions: string[];
  materialRecommendations: Record<string, string>;
  predictedIndoorTemp: number | null;

  // Step 4
  style: ArchStyle;
  budget: BudgetRange;

  // Step 5
  floorPlanSvg: string | null;

  // Actions
  setLocation: (loc: PlotLocation) => void;
  setClimateData: (data: ClimateData) => void;
  setRequirements: (req: Partial<Requirements>) => void;
  setAnalysisResults: (data: {
    ensScore: number;
    layoutSuggestions: string[];
    materialRecommendations: Record<string, string>;
    predictedIndoorTemp: number;
  }) => void;
  setStyle: (style: ArchStyle) => void;
  setBudget: (budget: BudgetRange) => void;
  setFloorPlan: (svg: string) => void;
  reset: () => void;
}

// ── Default requirements ───────────────────────────────────────────────────

const defaultRequirements: Requirements = {
  bedrooms: 2,
  bathrooms: 2,
  livingRooms: 1,
  kitchen: 1,
  parkingBays: 1,
  openSpacePercent: 20,
  floors: 1,
  buildingType: "low_rise",
  plotAreaSqm: 150,
  plotFacing: null,
  hasElderly: false,
  hasHomeOffice: false,
  vastuPreference: false,
};

// ── Store ──────────────────────────────────────────────────────────────────

export const useProjectStore = create<ProjectStore>()(
  persist(
    (set) => ({
      location: null,
      climateData: null,
      requirements: defaultRequirements,
      ensScore: null,
      layoutSuggestions: [],
      materialRecommendations: {},
      predictedIndoorTemp: null,
      style: null,
      budget: null,
      floorPlanSvg: null,

      setLocation: (loc) => set({ location: loc }),
      setClimateData: (data) => set({ climateData: data }),
      setRequirements: (req) =>
        set((state) => ({
          requirements: { ...state.requirements, ...req },
        })),
      setAnalysisResults: (data) =>
        set({
          ensScore: data.ensScore,
          layoutSuggestions: data.layoutSuggestions,
          materialRecommendations: data.materialRecommendations,
          predictedIndoorTemp: data.predictedIndoorTemp,
        }),
      setStyle: (style) => set({ style }),
      setBudget: (budget) => set({ budget }),
      setFloorPlan: (svg) => set({ floorPlanSvg: svg }),
      reset: () =>
        set({
          location: null,
          climateData: null,
          requirements: defaultRequirements,
          ensScore: null,
          layoutSuggestions: [],
          materialRecommendations: {},
          predictedIndoorTemp: null,
          style: null,
          budget: null,
          floorPlanSvg: null,
        }),
    }),
    {
      name: "ecohomes-project", // persisted in localStorage
    }
  )
);
